name: "CodeGuardian Code Review Action"
description: "Perform code reviews and comment on diffs using OpenAI API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  KEY:
    description: "CodeGuardian key"
    required: true
    default: ""
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Make script executable
      shell: bash
      run: chmod +x ${{ github.action_path }}/run_code_review.sh

    - name: Run code review script
      run: ${{ github.action_path }}/run_code_review.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
        KEY: ${{ inputs.KEY }}
branding:
  icon: "aperture"
  color: "green"